plugins {
    id 'application'
}

dependencies {
    implementation project(':relang-core')
    implementation libs.graalvm.truffle.api
    implementation libs.gson

    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
}

application {
    mainClass = 'com.relang.lsp.ReLangLspLauncher'
}
